### ISSUE TITLE
话说wsa可以无法运行碧蓝档案可以使用此项目中的方法吗

### ISSUE THREAD

**Issue by milkdog114514** [natsumerinchan/libhoudini-package#13]

**Comment by natsumerinchan** [comment]
wsa 内核源码: https://github.com/microsoft/WSA-Linux-Kernel.git

5.10的esdfs: https://chromium.googlesource.com/chromiumos/third_party/kernel/+/refs/heads/chromeos-5.10/fs/esdfs/

去arch/Kconfig 加上 source "fs/esdfs/Kconfig"

再去configs/wsa/config-wsa-5.10 加上 CONFIG_ESD_FS=y

编译试一试

**Comment by natsumerinchan** [comment]
但咱没有wsa本体的源码，好像不行

**Comment by milkdog114514** [comment]
sadge🥺

**Comment by natsumerinchan** [comment]
我已经给内核开启sdcardfs了 [kernel.zip](https://github.com/natsumerinchan/libhoudini-package/files/10752501/kernel.zip)
```
redfin:/ # zcat /proc/config.gz | grep SDCARD
CONFIG_SDCARD_FS=y
```
但咱没有wsa的本体源码，无法revert[该提交](https://github.com/supremegamers/device_generic_common/commit/ff34d6d549f026156188cf1467f26628e5cac658)，所以BA还是打不开

`ziparchive: Unable to open '/data/app/~~AewFIHFHG9pquPsTyWFgsw==/com.nexon.bluearchive-Cw6mmULmNTJdS3KEoOKvtA==/split_config.arm64_v8a.dm': No such file or directory`
